language: java
jdk:
    - openjdk7
    - oraclejdk7
#script: mkdir -p java/bin && cd java/bin && javac -d . -sourcepath ../src -cp ../lib/commons-codec-1.4.jar:../lib/commons-httpclient-3.1.jar:../lib/commons-logging-1.1.1.jar:../lib/junit-4.7.jar:../lib/log4j-1.2.15.jar ../src/com/kaltura/client/test/KalturaTestSuite.java
